### ISSUE TITLE
missing donate/support link

### ISSUE THREAD

**Issue by kamilmirza** [LumitoLuma/OpenSSH-for-Windows#4]
I have been struggling to get latest openssh binaries for windows
thank you so much the installer 
please add donate/support link so I can show my appreciation :)

**Comment by LumitoLuma** [comment]
Thank you so much for using my software, I'm really glad that you love it!

I currently do not accept donations. However, if you want to help me, share this program with people you know. I would really appreciate that.

If you have any problems with OpenSSHforWindows-Installer, please ask them here. Thanks!
